package de.guehring.footballserver.league;

import de.guehring.footballserver.team.Team;
import jakarta.persistence.*;

@Entity
public class League {
    // Attributes
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private int id;

    private String leagueName;
    // Constructor (Tip: Can be generated by Lombok with @NoArgsConstructor and @AllArgsConstructor)
    public League(int id, String leagueName) {
        this.id = id;
        this.leagueName = leagueName;
    }

    public League() {
    }


    // Getters and Setters (Tip: Can be generated by Lombok with @Getter and @Setter)
    public int getId() {
        return id;
    }

    public void setId(int id) {
        this.id = id;
    }

    public String getLeagueName() {
        return leagueName;
    }

    public void setLeagueName(String leagueName) {
        this.leagueName = leagueName;
    }
}
